ajout(api): ajout drizzle orm
ArmandThomas/MIA15 pull request #7
Opened 2024-05-27 16:05 UTC by sofiane-msatfa

A merge après la #6

2024-05-27 17:40 UTC, ArmandThomas commented on apps/api/src/controllers/country-controller.ts
> +const createCountry: RequestHandler = async (req, res, next) => {
Je pense pas qu'on aura le besoin de créer un country

2024-05-27 17:43 UTC, ArmandThomas commented on apps/api/src/database/schema/countries.ts
> +  name: varchar("name", { length: 256 }).unique().notNull(),
Si on veut partir sur une table country qu'on lie après, il faudrait aussi le code 3 caractères et 2

2024-05-27 17:45 UTC, ArmandThomas commented on apps/api/src/services/country-service.ts
> +async function create(country: NewCountry): Promise<Country> {
Pareil je pense qu'on aura pas besoin de créer de pays

2024-05-27 17:47 UTC, ArmandThomas requested changes
Juste pour t'embêter ;)

2024-05-27 20:26 UTC, sofiane-msatfa commented on apps/api/src/controllers/country-controller.ts
> +const createCountry: RequestHandler = async (req, res, next) => {
C'était plus pour l'exemple, mais maintenant que tu le dis c'est vrai qu'on aura pas du tout besoin de faire d'insert depuis l'api !

2024-05-27 20:42 UTC, sofiane-msatfa commented on apps/api/src/routes/greetings-router.ts
> +import { greetingsController } from "@/controllers/greetings-controller.js";
Je pense que c'est mieux d'encapsuler les méthodes dans un objet pour:
- éviter les collisions de nom si jamais on utilise des utilitaires avec des nombres similaires
- pouvoir changer facilement si on souhaite passer vers quelques chose de plus robuste utilisant des classes et de l'injection de dépendances
- comprendre directement ce que fait le code (cad appeler la méthode d'un controller)

2024-05-28 07:36 UTC, ArmandThomas approved these changes

2024-05-28 09:17 UTC, merged